name: Croiseursandernosiens
favicon: null
layout_spectrum: 0.8855950469151139
typography_spectrum: 0.8778302751015872
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.9087740066461265
  lightness: 0.5704848477616906
  saturation: 0.5134292200673372
  rhythmicContrast: 0.8270490176510066
purpose: []
